<?php

namespace App\Modules\Hr\Services;

use App\Models\EmployeeTransfer;
use App\Models\Invoice;
use App\Models\Shop;
use App\Models\User;
use Illuminate\Support\Carbon;

/**
 * Branch Bonus — pool-and-share model.
 *
 *   Branch Bonus Pool = branch approved sales × the BRANCH's bonus %
 *   Each employee actively assigned to that branch during a period receives an
 *   EQUAL share of the pool: share = pool / headcount.
 *
 * Because employees are transferred in/out, a branch's headcount changes over
 * time. We therefore split each employee's active-branch timeline into
 * sub-periods where the branch headcount is constant, compute the pool and the
 * equal share for each, and sum the employee's shares.
 *
 * The branch a sale belongs to is the invoice's shop_id (frozen at creation),
 * so history is always accurate regardless of later transfers.
 */
class BranchBonusService
{
    public const APPROVED = 'approved';

    public function __construct(private ActiveBranchService $activeBranch) {}

    /** Approved sales generated by a branch within [from, to]. */
    public function branchSalesTotal(int $shopId, Carbon $from, Carbon $to): float
    {
        return (float) Invoice::query()
            ->where('shop_id', $shopId)
            ->where('status', self::APPROVED)
            ->whereBetween('date', [$from->toDateString(), $to->toDateString()])
            ->sum('total_amount');
    }

    /**
     * IDs of employees whose ACTIVE branch is $shopId on $date. Equal-share
     * eligibility is based on this set (its size is the headcount / divisor).
     *
     * @return int[]
     */
    public function activeEmployeeIds(int $shopId, Carbon $date): array
    {
        // Employees whose primary branch is this shop (active employment only).
        $primaryHere = User::query()
            ->whereIn('role', ['manager', 'sales'])
            ->where('status', 'active')
            ->where('shop_id', $shopId)
            ->pluck('id')
            ->all();

        // Of those, anyone temporarily transferred AWAY on this date is excluded.
        $awayIds = EmployeeTransfer::query()
            ->whereIn('status', EmployeeTransfer::EFFECTIVE_STATUSES)
            ->whereIn('user_id', $primaryHere)
            ->where('temporary_branch_id', '!=', $shopId)
            ->whereDate('start_date', '<=', $date->toDateString())
            ->whereDate('end_date', '>=', $date->toDateString())
            ->pluck('user_id')
            ->all();

        // Employees temporarily transferred INTO this shop on this date.
        $transferredIn = EmployeeTransfer::query()
            ->whereIn('status', EmployeeTransfer::EFFECTIVE_STATUSES)
            ->where('temporary_branch_id', $shopId)
            ->whereDate('start_date', '<=', $date->toDateString())
            ->whereDate('end_date', '>=', $date->toDateString())
            ->whereHas('user', fn ($q) => $q->whereIn('role', ['manager', 'sales'])->where('status', 'active'))
            ->pluck('user_id')
            ->all();

        $ids = array_diff($primaryHere, $awayIds);
        $ids = array_unique(array_merge($ids, $transferredIn));

        return array_values($ids);
    }

    public function headcount(int $shopId, Carbon $date): int
    {
        return count($this->activeEmployeeIds($shopId, $date));
    }

    /**
     * The branch bonus an individual employee earns over [from, to], summing
     * their equal shares across every branch/headcount sub-period.
     *
     * @return array{ total: float, segments: array<int, array<string, mixed>> }
     */
    public function forEmployee(User $employee, Carbon $from, Carbon $to): array
    {
        $total = 0.0;
        $out   = [];

        // The employee's own active-branch timeline (primary vs temporary).
        foreach ($this->activeBranch->activeBranchSegments($employee, $from, $to) as $seg) {
            $shopId = $seg['shop_id'];
            if (! $shopId) {
                continue;
            }
            $pct = (float) (Shop::whereKey($shopId)->value('branch_bonus_percent') ?? 0);

            // Walk the segment, grouping consecutive days with equal headcount so
            // we run one sales query per constant-headcount sub-period.
            $cursor = $seg['from']->copy();
            $segEnd = $seg['to'];

            while ($cursor->lessThanOrEqualTo($segEnd)) {
                $hc   = $this->headcount($shopId, $cursor);
                $next = $cursor->copy()->addDay();
                while ($next->lessThanOrEqualTo($segEnd) && $this->headcount($shopId, $next) === $hc) {
                    $next->addDay();
                }
                $subEnd = $next->copy()->subDay();

                if ($hc > 0 && $pct > 0) {
                    $sales = $this->branchSalesTotal($shopId, $cursor, $subEnd);
                    $pool  = $sales * $pct / 100;
                    $share = $pool / $hc;
                    $total += $share;

                    $out[] = [
                        'shop_id'     => $shopId,
                        'from'        => $cursor->toDateString(),
                        'to'          => $subEnd->toDateString(),
                        'branch_pct'  => $pct,
                        'branch_sales'=> round($sales, 2),
                        'pool'        => round($pool, 2),
                        'headcount'   => $hc,
                        'share'       => round($share, 2),
                    ];
                }
                $cursor = $next;
            }
        }

        return ['total' => round($total, 2), 'segments' => $out];
    }
}
