<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Services\Reports\ReportExportService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

/**
 * Reports unique to the perfume-composition workflow — how much of each oil
 * and each bottle was actually used across real Compound Product sales
 * (invoice_items.role = 'oil'|'bottle', grouped under a parent Compound
 * Product line). Never derived from a stored recipe — Compound Products
 * have none; every number here comes from what was actually sold.
 */
class AdminPerfumeReportController extends Controller
{
    public function __construct(private ReportExportService $exportService) {}

    private function parseDates(Request $request): array
    {
        if ($request->filled('from') && $request->filled('to')) {
            return [$request->get('from'), $request->get('to')];
        }
        $period = $request->get('period', 'month');
        $from = match ($period) {
            'today' => now()->startOfDay()->toDateString(),
            'week'  => now()->startOfWeek()->toDateString(),
            'month' => now()->startOfMonth()->toDateString(),
            'year'  => now()->startOfYear()->toDateString(),
            default => now()->startOfMonth()->toDateString(),
        };
        return [$from, now()->toDateString()];
    }

    private function usageQuery(string $role, string $from, string $to, ?int $shopId)
    {
        $q = DB::table('invoice_items as ii')
            ->join('invoices as inv', 'inv.id', '=', 'ii.invoice_id')
            ->join('products as p', 'p.id', '=', 'ii.product_id')
            ->where('ii.role', $role)
            ->where('inv.status', 'approved')
            ->whereBetween('inv.date', [$from, $to]);

        if ($shopId) {
            $q->where('inv.shop_id', $shopId);
        }

        return $q;
    }

    // ── GET /api/admin/reports/perfume/summary ──────────────────────────────
    public function summary(Request $request)
    {
        [$from, $to] = $this->parseDates($request);
        $shopId = $request->filled('shop_id') ? (int) $request->get('shop_id') : null;

        // NOTE: ii.price here is the oil/bottle product's own configured selling
        // price (price_per_gram for oils, selling_price for bottles) — see
        // SalesService::resolveConfiguredUnitPrice(). It is revenue generated by
        // that component, never a cost figure — no COGS is captured at sale time
        // anywhere in this schema, so we must not label it "cost".
        $oils = $this->usageQuery('oil', $from, $to, $shopId)
            ->selectRaw('p.id, p.name, p.sku, SUM(ii.quantity) as total_qty, COUNT(*) as usage_count, SUM(ii.quantity * ii.price) as revenue_value')
            ->groupBy('p.id', 'p.name', 'p.sku')
            ->orderByDesc('total_qty')
            ->get()
            ->map(fn ($r) => [
                'id' => $r->id, 'name' => $r->name, 'sku' => $r->sku,
                'total_qty' => round((float) $r->total_qty, 3), 'usage_count' => (int) $r->usage_count,
                'revenue_value' => round((float) $r->revenue_value, 2),
            ]);

        $bottles = $this->usageQuery('bottle', $from, $to, $shopId)
            ->selectRaw('p.id, p.name, p.sku, SUM(ii.quantity) as total_qty, COUNT(*) as usage_count, SUM(ii.quantity * ii.price) as revenue_value')
            ->groupBy('p.id', 'p.name', 'p.sku')
            ->orderByDesc('total_qty')
            ->get()
            ->map(fn ($r) => [
                'id' => $r->id, 'name' => $r->name, 'sku' => $r->sku,
                'total_qty' => round((float) $r->total_qty, 3), 'usage_count' => (int) $r->usage_count,
                'revenue_value' => round((float) $r->revenue_value, 2),
            ]);

        $compoundSalesCount = DB::table('invoice_items')
            ->join('invoices', 'invoices.id', '=', 'invoice_items.invoice_id')
            ->whereNotNull('invoice_items.parent_product_id')
            ->where('invoice_items.role', 'oil')
            ->where('invoices.status', 'approved')
            ->whereBetween('invoices.date', [$from, $to])
            ->when($shopId, fn ($q) => $q->where('invoices.shop_id', $shopId))
            ->count();

        return response()->json([
            'message' => 'ok',
            'data' => [
                'period' => ['from' => $from, 'to' => $to],
                'compound_sales_count' => $compoundSalesCount,
                'oils' => $oils,
                'bottles' => $bottles,
                'total_oil_qty' => round((float) $oils->sum('total_qty'), 3),
                'total_bottle_qty' => round((float) $bottles->sum('total_qty'), 3),
                'total_oil_revenue' => round((float) $oils->sum('revenue_value'), 2),
                'total_bottle_revenue' => round((float) $bottles->sum('revenue_value'), 2),
            ],
        ]);
    }

    // ── GET /api/admin/reports/perfume/trend — monthly oil+bottle qty ───────
    public function trend(Request $request)
    {
        [$from, $to] = $this->parseDates($request);
        $shopId = $request->filled('shop_id') ? (int) $request->get('shop_id') : null;

        $byMonth = function (string $role) use ($from, $to, $shopId) {
            return $this->usageQuery($role, $from, $to, $shopId)
                ->selectRaw("DATE_FORMAT(inv.date, '%Y-%m') as month, SUM(ii.quantity) as qty")
                ->groupBy('month')->orderBy('month')
                ->pluck('qty', 'month');
        };

        $oilByMonth = $byMonth('oil');
        $bottleByMonth = $byMonth('bottle');
        $months = $oilByMonth->keys()->merge($bottleByMonth->keys())->unique()->sort()->values();

        $rows = $months->map(fn ($m) => [
            'month' => $m,
            'oil_qty' => round((float) ($oilByMonth[$m] ?? 0), 3),
            'bottle_qty' => round((float) ($bottleByMonth[$m] ?? 0), 3),
        ]);

        return response()->json(['message' => 'ok', 'data' => $rows]);
    }

    // ── GET /api/admin/reports/perfume/export?format=pdf|excel&type=oil|bottle ──
    public function export(Request $request)
    {
        [$from, $to] = $this->parseDates($request);
        $shopId = $request->filled('shop_id') ? (int) $request->get('shop_id') : null;
        $type = $request->get('type', 'oil') === 'bottle' ? 'bottle' : 'oil';

        $rows = $this->usageQuery($type, $from, $to, $shopId)
            ->selectRaw('p.name, p.sku, SUM(ii.quantity) as total_qty, COUNT(*) as usage_count, SUM(ii.quantity * ii.price) as revenue_value')
            ->groupBy('p.id', 'p.name', 'p.sku')
            ->orderByDesc('total_qty')
            ->get();

        $columns = ['المنتج', 'الكود', 'الكمية المستخدمة', 'عدد مرات الاستخدام', 'قيمة الاستهلاك (سعر البيع)'];
        $tableRows = $rows->map(fn ($r) => [
            $r->name, $r->sku, round((float) $r->total_qty, 3), (int) $r->usage_count, round((float) $r->revenue_value, 2),
        ])->all();

        $title = $type === 'oil' ? 'تقرير استهلاك الزيوت' : 'تقرير استهلاك الزجاجات';
        $filters = array_filter(['من' => $from, 'إلى' => $to]);

        return $request->input('format') === 'excel'
            ? $this->exportService->excel($title, $columns, $tableRows, $filters, [4])
            : $this->exportService->pdf($title, $columns, $tableRows, $filters);
    }
}
